CREATE TABLE IF NOT EXISTS events (
  id BIGSERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  location VARCHAR(255) NOT NULL,
  event_date VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS "query" (
  id BIGSERIAL PRIMARY KEY,
  full_name VARCHAR(255), email VARCHAR(255), phone VARCHAR(255),
  event_type VARCHAR(255), event_date VARCHAR(255), city_venue VARCHAR(255),
  special_requirements VARCHAR(255), message VARCHAR(255)
);
ALTER TABLE IF EXISTS "query" ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS "query" ADD COLUMN IF NOT EXISTS status VARCHAR(24) NOT NULL DEFAULT 'NEW';
ALTER TABLE IF EXISTS "query" ADD COLUMN IF NOT EXISTS follow_up_date DATE;
ALTER TABLE IF EXISTS "query" ADD COLUMN IF NOT EXISTS follow_up_note VARCHAR(2000);
ALTER TABLE IF EXISTS "query" ADD COLUMN IF NOT EXISTS next_action VARCHAR(500);
ALTER TABLE IF EXISTS "query" ADD COLUMN IF NOT EXISTS guest_count INTEGER;
ALTER TABLE IF EXISTS "query" ADD COLUMN IF NOT EXISTS budget VARCHAR(120);

CREATE TABLE IF NOT EXISTS admin_users (
  id BIGSERIAL PRIMARY KEY, email VARCHAR(254) NOT NULL UNIQUE,
  password_hash VARCHAR(100) NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS gallery_categories (
  id BIGSERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL, slug VARCHAR(120) NOT NULL UNIQUE,
  description VARCHAR(1000), cover_image VARCHAR(500), published BOOLEAN NOT NULL DEFAULT FALSE,
  display_order INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS gallery_images (
  id BIGSERIAL PRIMARY KEY, category_id BIGINT NOT NULL REFERENCES gallery_categories(id) ON DELETE CASCADE,
  storage_key VARCHAR(300) NOT NULL, alt_text VARCHAR(300), display_order INTEGER NOT NULL DEFAULT 0,
  published BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS testimonials (
  id BIGSERIAL PRIMARY KEY, name VARCHAR(255) NOT NULL, event_type VARCHAR(255), location VARCHAR(255),
  review VARCHAR(3000) NOT NULL, published BOOLEAN NOT NULL DEFAULT FALSE,
  display_order INTEGER NOT NULL DEFAULT 0, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS managed_services (
  id BIGSERIAL PRIMARY KEY, name VARCHAR(255) NOT NULL, description VARCHAR(2000), image_url VARCHAR(500),
  published BOOLEAN NOT NULL DEFAULT TRUE, display_order INTEGER NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_gallery_images_category_order ON gallery_images(category_id, display_order, id);
CREATE INDEX IF NOT EXISTS idx_query_created_at ON "query"(created_at DESC);
