package com.sagar.eventmanagement.gallery;
import com.sagar.eventmanagement.entity.*; import com.sagar.eventmanagement.repository.*; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import org.springframework.beans.factory.annotation.Value; import org.springframework.core.io.*; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile; import org.springframework.web.server.ResponseStatusException; import javax.imageio.ImageIO; import javax.imageio.ImageReader; import javax.imageio.stream.ImageInputStream; import java.util.Iterator; import java.io.*; import java.nio.file.*; import java.util.*;
@RestController @RequestMapping("/api/gallery") public class GalleryController {
 private final GalleryCategoryRepository categories; private final GalleryImageRepository images; private final Path root;
 public GalleryController(GalleryCategoryRepository c,GalleryImageRepository i,@Value("${app.upload.directory:./uploads}") String dir)throws IOException{categories=c;images=i;root=Path.of(dir).toAbsolutePath().normalize();Files.createDirectories(root);}
 public record CategoryInput(@NotBlank String name,@NotBlank String slug,String description,String coverImage,boolean published,int displayOrder){}
 public record ImageView(Long id,String url,String altText,int displayOrder,boolean published){}
 public record CategoryView(Long id,String name,String slug,String description,String coverImage,boolean published,int displayOrder,List<ImageView> images){}
 private CategoryView view(GalleryCategory c,boolean pub){var list=(pub?images.findByCategorySlugAndPublishedTrueOrderByDisplayOrderAscIdAsc(c.getSlug()):images.findByCategoryIdOrderByDisplayOrderAscIdAsc(c.getId())).stream().filter(x->!pub||x.isPublished()).map(x->new ImageView(x.getId(),"/api/gallery/media/"+x.getStorageKey(),x.getAltText(),x.getDisplayOrder(),x.isPublished())).toList();return new CategoryView(c.getId(),c.getName(),c.getSlug(),c.getDescription(),c.getCoverImage(),c.isPublished(),c.getDisplayOrder(),list);}
 @GetMapping("/categories") public List<CategoryView> publicCategories(){return categories.findByPublishedTrueOrderByDisplayOrderAsc().stream().map(c->view(c,true)).toList();}
 @GetMapping("/categories/{slug}") public CategoryView publicCategory(@PathVariable String slug){var c=categories.findBySlug(slug).filter(GalleryCategory::isPublished).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));return view(c,true);}
 @GetMapping("/categories/{slug}/images") public List<ImageView> publicImages(@PathVariable String slug){return publicCategory(slug).images();}
 @GetMapping("/admin/categories") public List<CategoryView> adminCategories(){return categories.findAllByOrderByDisplayOrderAsc().stream().map(c->view(c,false)).toList();}
 @PostMapping("/admin/categories") public CategoryView create(@Valid @RequestBody CategoryInput in){String slug=normalizeSlug(in.slug());validateSlug(slug);if(categories.existsBySlug(slug))throw new ResponseStatusException(HttpStatus.CONFLICT,"Slug already exists");var c=new GalleryCategory();apply(c,in,slug);return view(categories.save(c),false);}
 @PutMapping("/admin/categories/{id}") public CategoryView update(@PathVariable Long id,@Valid @RequestBody CategoryInput in){var c=categories.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));String slug=normalizeSlug(in.slug());validateSlug(slug);if(categories.findBySlug(slug).filter(x->!x.getId().equals(id)).isPresent())throw new ResponseStatusException(HttpStatus.CONFLICT,"Slug already exists");apply(c,in,slug);return view(categories.save(c),false);}
 private String normalizeSlug(String slug){return slug==null?"":slug.trim().toLowerCase(Locale.ROOT);}
 private void validateSlug(String slug){if(!slug.matches("[a-z0-9]+(?:-[a-z0-9]+)*"))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Slug must contain lowercase letters, numbers, and single hyphens");}
 private void apply(GalleryCategory c,CategoryInput i,String slug){c.setName(i.name().trim());c.setSlug(slug);c.setDescription(i.description());c.setCoverImage(i.coverImage());c.setPublished(i.published());c.setDisplayOrder(i.displayOrder());}
 @DeleteMapping("/admin/categories/{id}") public void deleteCategory(@PathVariable Long id){var c=categories.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));for(var image:c.getImages())remove(image.getStorageKey());categories.delete(c);}
 @PostMapping(value="/admin/categories/{id}/images",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) public List<ImageView> upload(@PathVariable Long id,@RequestParam("files") List<MultipartFile> files)throws IOException{var c=categories.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));if(files.isEmpty()||files.size()>20)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Upload between 1 and 20 images");var result=new ArrayList<ImageView>();for(var file:files){if(file.isEmpty())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Empty image file");if(file.getSize()>10*1024*1024)throw new ResponseStatusException(HttpStatus.PAYLOAD_TOO_LARGE,"Each image must be at most 10 MB");String declared=file.getContentType();if(!List.of("image/jpeg","image/png","image/gif").contains(declared))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Only JPEG, PNG, and GIF images are allowed");String format;try(ImageInputStream stream=ImageIO.createImageInputStream(file.getInputStream())){Iterator<ImageReader> readers=ImageIO.getImageReaders(stream);if(!readers.hasNext())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Invalid image file");ImageReader reader=readers.next();try{reader.setInput(stream,true,true);format=reader.getFormatName().toLowerCase(Locale.ROOT);int width=reader.getWidth(0),height=reader.getHeight(0);if(width<1||height<1||width>8000||height>8000||(long)width*height>30_000_000L)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Image dimensions exceed the 30-megapixel limit");if(reader.read(0)==null)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Invalid image file");}finally{reader.dispose();}}catch(ResponseStatusException e){throw e;}catch(Exception e){throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Invalid image file");}String expected=switch(format){case "jpeg","jpg"->"image/jpeg";case "png"->"image/png";case "gif"->"image/gif";default->"";};if(!declared.equals(expected))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Image content does not match its declared type");String ext=format.equals("jpeg")?"jpg":format;String key=UUID.randomUUID()+"."+ext;Path target=root.resolve(key).normalize();if(!target.startsWith(root))throw new ResponseStatusException(HttpStatus.BAD_REQUEST);Files.copy(file.getInputStream(),target);var image=new GalleryImage();image.setCategory(c);image.setStorageKey(key);image.setPublished(false);image.setDisplayOrder(images.findByCategoryIdOrderByDisplayOrderAscIdAsc(id).size());result.add(imageView(images.save(image)));}return result;}
 private ImageView imageView(GalleryImage x){return new ImageView(x.getId(),"/api/gallery/media/"+x.getStorageKey(),x.getAltText(),x.getDisplayOrder(),x.isPublished());}
 @PutMapping("/admin/images/{id}") public ImageView editImage(@PathVariable Long id,@RequestBody Map<String,Object> body){var x=images.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));if(body.containsKey("altText"))x.setAltText(Objects.toString(body.get("altText"),""));if(body.containsKey("published"))x.setPublished(Boolean.parseBoolean(body.get("published").toString()));if(body.containsKey("displayOrder"))x.setDisplayOrder(Integer.parseInt(body.get("displayOrder").toString()));return imageView(images.save(x));}
 @DeleteMapping("/admin/images/{id}") public void deleteImage(@PathVariable Long id){var x=images.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));remove(x.getStorageKey());images.delete(x);}
 @GetMapping("/media/{key:.+}") public ResponseEntity<Resource> media(@PathVariable String key)throws IOException{if(key.contains("/")||key.contains("\\")||key.contains(".."))throw new ResponseStatusException(HttpStatus.NOT_FOUND);var image=images.findByStorageKey(key).filter(GalleryImage::isPublished).filter(x->x.getCategory().isPublished()).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));Path p=root.resolve(image.getStorageKey()).normalize();if(!p.startsWith(root)||!Files.isRegularFile(p))throw new ResponseStatusException(HttpStatus.NOT_FOUND);return ResponseEntity.ok().contentType(MediaTypeFactory.getMediaType(p.getFileName().toString()).orElse(MediaType.APPLICATION_OCTET_STREAM)).header("X-Content-Type-Options","nosniff").body(new FileSystemResource(p));}
 private void remove(String key){try{Files.deleteIfExists(root.resolve(key).normalize());}catch(IOException ignored){}}
}
